### PR TITLE
Updated cfpb-chart-builder to 0.0.8, shrinkwrapped

### PR DESCRIPTION
**Pull request by mistergone**
Updated cfpb-chart-builder to 0.0.8, shrinkwrapped

## Changes
- Updated cfpb-chart-builder to `0.0.8`
- ran `npm shrinkwrap`
## Review
- @cfarm @marteki 

[Preview this PR without the whitespace changes](?w=0)

### CODE REVIEW

**Comment by marteki** [comment]
Checking locally after `gulp watch`: the year is missing from the X axis.

Example:
screen shot 2016-12-13 at 6 49 49 pm

**Comment by mistergone** [comment]
Fixes in `bar.js` and `line.js` got lost, possibly in a merge somewhere. They are back in there now.

**Comment by cfarm** [comment]
Code looks good. waiting for @marteki to test it works!

**Comment by marteki** [comment]
The years are back! The code is releasing properly! [insert-release-the-kraken-gif-here]

**Pull request merged**
