### PR TITLE
Another update to the data files

### PR DESCRIPTION
**Pull request by marteki**
We got another update to the data early this morning.

## Changes

- 80 CSV files with end dates of October 2016

## Review

- @cfarm 
- @mistergone 
- @hillaryj
- @ajbush 
- @nataliafitzgerald 
- @schaferjh 

[Preview this PR without the whitespace changes](?w=0)

### CODE REVIEW

**Comment by marteki** [comment]
Nota bene: there have been significant changes to the map data files. In particular, some states are now showing YoY change values of over 60%, 70%, or even 100%.

**Comment by cfarm** [comment]
options for the map legend updates

screen shot 2016-12-13 at 3 08 58 pm

screen shot 2016-12-13 at 3 12 38 pm

**Comment by marteki** [comment]
We're going with '-25% or less' and '25% or more'.

**Comment by cfarm** [comment]
Testing this out now.

**Comment by cfarm** [comment]
Testing out new data. This is the only outlier graph I found - it works, just big values!

http://localhost:3000/charts/student-loans/borrower-age/figure-4b__65-and-older__student-loans.html
screen shot 2016-12-13 at 4 45 19 pm

**Comment by cfarm** [comment]
Getting this into this pr and chart builder.

screen shot 2016-12-13 at 5 09 38 pm

**Comment by cfarm** [comment]
HEre's a good example of the new yOy values on a map
screen shot 2016-12-13 at 5 21 30 pm

107% lookin just fine!

**Comment by cfarm** [comment]
OK'ed on my end for merge. All graphs with updated data are looking functional and purty as ever. 

We'll get this in with the updated chart builder code.

**Comment by marteki** [comment]
Merging!

**Pull request merged**
