### PR TITLE
update chart-builder to 0.0.7 for legend updates

### PR DESCRIPTION
**Pull request by cfarm**
Get new legend position from latest chart builder

### CODE REVIEW

**Comment by mistergone** [comment]
0.0.7 has now been published!

**Comment by cfarm** [comment]
yay! ill update this bracnh for moar review

**Comment by marteki** [comment]
what legend updates should we be seeing when we review this?

**Comment by cfarm** [comment]
@marteki still working on this. I'll post a screenshot when it's ready for review again

**Comment by cfarm** [comment]
## NEW IN VERSION 0.0.7!!!

* Properly positioned line graph legend!!!
* Stacked X axis labels!!!

screen shot 2016-12-13 at 3 43 05 pm


screen shot 2016-12-13 at 3 43 20 pm

**Comment by marteki** [comment]
Locally built version matches the description and screenshots above! Now testing on Wagtail...

**Comment by cfarm** [comment]
hold on ! v0.0.8 coming soon :)

**Comment by mistergone** [comment]
This might be superseded by #34

**Comment by marteki** [comment]
Properly positioned legend and stacked X axis labels appearing in Wagtail. I think that goes for either this PR or #34.

**Comment by cfarm** [comment]
word this is obsoleted by #34

**Pull request closed without merging**
