### PR TITLE
Lint js files

### PR DESCRIPTION
**Pull request by cfarm**
Cleaning up JS files by using our .eslintrc settings

## Changes

- Reformatted files based on linter errors
- Added JSDocs to undocumented functions
-

## Testing

- check out branch
- run `./setup-sh`
- run `gulp watch` and check page and charts for broken JS or JS errors (2 persistent errors from Github API are expected and can be ignored, these happen if your Personal Access Token has not been set up, see readme)
- run `gulp release` and check compiled files in `/charts/` for errors
- run 'gulp lint' to check for linter errors

## Review

- @marteki 
- @mistergone 

[Preview this PR without the whitespace changes](?w=0)

## Todos

I didn't fix 2 files with 'quote is redundant for object properties' errors.  These will be done in future refactors - when we have TDD set up so we can better catch any errors in changes to those important files

### CODE REVIEW

**Comment by marteki** [comment]
Not part of the review, but: do we have a policy or something on which version of `gulp-eslint` we're using? Right now, we're on 2.0.0; do we want to upgrade to 3.x soon?

```
~/Repositories/cfpb/consumer-credit-trends master* 👾  npm outdated
Package      Current  Wanted  Latest  Location
gulp-eslint    2.0.0   2.0.0   3.0.1  consumer-credit-trends
```

**Review by marteki — CHANGES_REQUESTED** [review]
On running `gulp lint`, I'm getting a whole mess of errors and warnings besides "Properties shouldn't be quoted...":

```
[lots and lots of errors and warnings around many files]
✖ 363 problems (82 errors, 281 warnings)

[11:51:01] Finished 'lint:scripts' after 4.21 s
[11:51:01] 
/Users/reedm/Repositories/cfpb/consumer-credit-trends/gulp/tasks/browser-sync.js
  8:2  error  Expected indentation of 2 space characters but found 1  indent

✖ 1 problem (1 error, 0 warnings)
[11:51:01] Finished 'lint:build' after 6.28 s
```

**Comment by mistergone** [comment]
I see a lot of linter errors, too, but I'd rather fix them while refactoring than go back and spend a lot of effort cleaning up what is supposed to be very temporary code.

**Comment by mistergone** [comment]
Oh, and since I don't think we should fix all these linting errors right now:

👍

**Comment by marteki** [comment]
@mistergone Isn't this HTML/CSS/JS the code that the backend will be transferring into Wagtail from this repo?

I know that the manual copy-paste process was temporary; how temporary is the actual creation of front-end code? And if that's temporary, where will the front-end code for this project be coming from?

**Comment by marteki** [comment]
@mistergone Ah, maybe I understand now. You're talking about not fixing the generated HTML files? Okay, I could see that being a "not right now, but fix the files that generate it" thing.

**Comment by mistergone** [comment]
@marteki - No, I mean lots of the JS is very rough and I'd prioritize a rewrite over a lint cleanup. The code that generates line and bar graphs need to be largely refactored. `cfpb-chart-builder` will be refactored, which will result in changes here as well. And while the build process is likely to continue to exist, the ways `charts.js` is written is largely unsustainable. This code was a patchwork meant to make a thing work in short order - fixing the lint errors right now does not feel like a priority to me.

**Comment by marteki** [comment]
Ah! Okay.

Then 👍 , since the major error-prone files are the ones you called out.

**Review by marteki — APPROVED** [review]

**Comment by cfarm** [comment]
Refactoring the JS is not the highest priority for this sprint, so in the meantime while we do bug fixes and get unit tests written, we need to lint our JS and follow our development standards. It will put us in a better place once we're ready to make major changes to the JavaScript.

**Comment by marteki** [comment]
For reference and bugfixing, here are the non-"Properties shouldn't be quoted..." errors and warnings I saw:

```
/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/bar.js
    5:49  error    Trailing spaces not allowed                                  no-trailing-spaces
   11:1   warning  Unexpected '@todo' comment                                   no-warning-comments
   14:1   warning  Missing JSDoc comment                                        require-jsdoc
   20:1   warning  Line 20 exceeds the maximum line length of 80                max-len
   24:4   error    Unnecessary semicolon                                        no-extra-semi
   31:1   warning  Missing JSDoc comment                                        require-jsdoc
   32:30  error    Expected error to be handled                                 handle-callback-err
   38:23  error    A leading decimal point can be confused with a dot           no-floating-decimal
   42:6   error    Missing semicolon                                            semi
   58:33  error    A constructor name should not start with a lowercase letter  new-cap
   66:1   warning  Missing JSDoc comment                                        require-jsdoc
   66:10  warning  'getMaxMonth' is defined but never used                      no-unused-vars
   70:10  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
   71:18  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
   73:4   error    Unnecessary semicolon                                        no-extra-semi
   79:1   warning  Missing JSDoc comment                                        require-jsdoc
   82:4   error    Expected indentation of 2 space characters but found 3       indent
   82:8   warning  There must be a space inside this paren                      space-in-parens
   83:5   error    Expected indentation of 5 space characters but found 4       indent
   85:15  error    Unexpected space between function name and paren             no-spaced-func
   86:7   error    Trailing spaces not allowed                                  no-trailing-spaces
   89:5   error    Expected indentation of 5 space characters but found 4       indent
   89:59  warning  There must be a space inside this paren                      space-in-parens
   93:3   error    Expected indentation of 3 space characters but found 2       indent
   98:1   warning  Missing JSDoc comment                                        require-jsdoc
  107:7   error    Expected indentation of 4 space characters but found 6       indent
  113:7   error    Expected indentation of 4 space characters but found 6       indent
  114:5   error    Expected indentation of 2 space characters but found 4       indent
  117:7   warning  'line' is defined but never used                             no-unused-vars
  122:42  warning  There must be a space inside this paren                      space-in-parens
  125:12  warning  There must be a space inside this paren                      space-in-parens
  126:12  warning  There must be a space inside this paren                      space-in-parens
  130:1   error    Trailing spaces not allowed                                  no-trailing-spaces
  136:31  error    Missing semicolon                                            semi
  140:1   warning  Missing JSDoc comment                                        require-jsdoc
  141:5   error    Expected indentation of 2 space characters but found 4       indent
  143:5   error    Expected indentation of 2 space characters but found 4       indent
  143:9   warning  There must be a space inside this paren                      space-in-parens
  150:5   error    Expected indentation of 2 space characters but found 4       indent

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/env.js
  1:1   error    Use the global form of 'use strict'                            strict
  1:1   warning  Line 1 exceeds the maximum line length of 80                   max-len
  1:1   error    Unexpected use of process.env                                  no-process-env
  1:13  error    ["GITHUB_ACCESS_TOKEN_KEY"] is better written in dot notation  dot-notation
  1:42  error    Strings must use singlequote                                   quotes
  1:84  error    Missing semicolon                                              semi

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/env_SAMPLE.js
  1:1   error  Use the global form of 'use strict'                            strict
  1:1   error  Unexpected use of process.env                                  no-process-env
  1:2   error  Newline required at end of file but not found                  eol-last
  1:13  error  ["GITHUB_ACCESS_TOKEN_KEY"] is better written in dot notation  dot-notation
  1:42  error  Strings must use singlequote                                   quotes
  1:57  error  Missing semicolon                                              semi

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/formatDates.js
   6:13  error    Trailing spaces not allowed                             no-trailing-spaces
   7:14  error    Trailing spaces not allowed                             no-trailing-spaces
   8:11  error    Trailing spaces not allowed                             no-trailing-spaces
  20:1   warning  Missing JSDoc comment                                   require-jsdoc
  23:7   warning  There must be a space inside this paren                 space-in-parens
  23:55  warning  There must be a space inside this paren                 space-in-parens
  24:7   error    Expected indentation of 4 space characters but found 6  indent
  24:17  warning  There must be a space inside this paren                 space-in-parens
  24:22  warning  There must be a space inside this paren                 space-in-parens
  31:1   warning  Missing JSDoc comment                                   require-jsdoc
  31:14  warning  There must be a space inside this paren                 space-in-parens
  31:25  warning  There must be a space inside this paren                 space-in-parens
  37:1   error    Trailing spaces not allowed                             no-trailing-spaces
  38:7   error    'year' is already defined                               no-redeclare
  38:34  warning  There must be a space inside this paren                 space-in-parens
  38:50  warning  There must be a space inside this paren                 space-in-parens

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/line.js
    5:5   warning  'formatDates' is defined but never used                      no-unused-vars
    6:49  error    Trailing spaces not allowed                                  no-trailing-spaces
    8:5   warning  'strToNum' is defined but never used                         no-unused-vars
   13:1   warning  Missing JSDoc comment                                        require-jsdoc
   19:1   warning  Line 19 exceeds the maximum line length of 80                max-len
   19:90  error    Trailing spaces not allowed                                  no-trailing-spaces
   24:4   error    Unnecessary semicolon                                        no-extra-semi
   34:1   warning  Missing JSDoc comment                                        require-jsdoc
   35:30  error    Expected error to be handled                                 handle-callback-err
   40:23  error    A leading decimal point can be confused with a dot           no-floating-decimal
   44:6   error    Missing semicolon                                            semi
   47:43  warning  There must be a space inside this paren                      space-in-parens
   54:1   warning  Line 54 exceeds the maximum line length of 80                max-len
   54:79  warning  There must be a space inside this paren                      space-in-parens
   57:77  error    Missing semicolon                                            semi
   61:68  error    Missing semicolon                                            semi
   68:9   error    Expected indentation of 6 space characters but found 8       indent
   86:9   error    Expected indentation of 6 space characters but found 8       indent
   92:7   error    Expected indentation of 4 space characters but found 6       indent
   92:35  error    A constructor name should not start with a lowercase letter  new-cap
   93:7   error    Expected indentation of 4 space characters but found 6       indent
   94:7   error    Expected indentation of 4 space characters but found 6       indent
   95:1   warning  Line 95 exceeds the maximum line length of 80                max-len
  101:1   warning  Missing JSDoc comment                                        require-jsdoc
  105:10  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
  106:18  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
  108:4   error    Unnecessary semicolon                                        no-extra-semi
  114:1   warning  Function 'reformatLineData' has a complexity of 7            complexity
  114:1   warning  Missing JSDoc comment                                        require-jsdoc
  120:39  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
  121:13  warning  use `Number(rawData[x].num)` instead                         no-implicit-coercion
  121:32  warning  use `Number(rawData[x].volume)` instead                      no-implicit-coercion
  124:36  error    Missing semicolon                                            semi
  130:10  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
  139:10  warning  use `Number(rawData[x].month)` instead                       no-implicit-coercion
  140:30  error    Missing semicolon                                            semi
  141:6   error    Trailing spaces not allowed                                  no-trailing-spaces
  144:42  warning  There must be a space inside this paren                      space-in-parens
  147:4   error    Unnecessary semicolon                                        no-extra-semi
  156:1   warning  Missing JSDoc comment                                        require-jsdoc
  157:7   error    'date' is already defined                                    no-redeclare
  159:7   warning  'y' is defined but never used                                no-unused-vars
  161:7   warning  'line' is defined but never used                             no-unused-vars
  166:40  warning  There must be a space inside this paren                      space-in-parens
  169:12  warning  There must be a space inside this paren                      space-in-parens
  170:12  warning  There must be a space inside this paren                      space-in-parens
  174:1   error    Trailing spaces not allowed                                  no-trailing-spaces
  180:31  error    Missing semicolon                                            semi
  183:1   warning  Missing JSDoc comment                                        require-jsdoc
  184:5   error    Expected indentation of 2 space characters but found 4       indent
  186:5   error    Expected indentation of 2 space characters but found 4       indent
  186:9   warning  There must be a space inside this paren                      space-in-parens
  193:5   error    Expected indentation of 2 space characters but found 4       indent
  196:2   error    Newline required at end of file but not found                eol-last

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/main.js
  3:1  warning  Line 3 exceeds the maximum comment line length of 80  max-len
  6:1  warning  Line 6 exceeds the maximum comment line length of 80  max-len

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/metadata.js
   3:8    warning  There must be a space inside this paren                     space-in-parens
   3:19   warning  There must be a space inside this paren                     space-in-parens
   9:13   error    Unexpected use of process.env                               no-process-env
  10:21   warning  There must be a space inside this paren                     space-in-parens
  10:34   warning  There must be a space inside this paren                     space-in-parens
  13:5    warning  Identifier 'most_recent_commit_date' is not in camel case   camelcase
  15:4    warning  There must be a space inside this paren                     space-in-parens
  15:15   error    Unexpected use of undefined                                 no-undefined
  15:53   warning  There must be a space inside this paren                     space-in-parens
  16:22   warning  There must be a space inside this paren                     space-in-parens
  18:4    warning  There must be a space inside this paren                     space-in-parens
  21:1    warning  Line 21 exceeds the maximum line length of 80               max-len
  21:3    warning  Unexpected console statement                                no-console
  21:15   warning  There must be a space inside this paren                     space-in-parens
  21:123  warning  There must be a space inside this paren                     space-in-parens
  21:124  error    Missing semicolon                                           semi
  25:1    error    Expected JSDoc for 'timestamp' but found 'Timestamp'        valid-jsdoc
  25:1    error    Missing JSDoc @returns for function                         valid-jsdoc
  31:9    warning  Identifier 'date_published' is not in camel case            camelcase
  32:12   warning  Identifier 'date_published' is not in camel case            camelcase
  33:10   error    Unexpected 'else' after 'return'                            no-else-return
  42:1    warning  Missing JSDoc comment                                       require-jsdoc
  44:28   warning  There must be a space inside this paren                     space-in-parens
  44:53   warning  There must be a space inside this paren                     space-in-parens
  47:25   warning  Properties shouldn't be quoted as all quotes are redundant  quote-props
  47:27   warning  Extra space after key 'path'                                key-spacing
  49:7    warning  Unexpected console statement                                no-console
  49:18   warning  There must be a space inside this paren                     space-in-parens
  49:26   warning  There must be a space inside this paren                     space-in-parens
  49:27   error    Missing semicolon                                           semi
  50:7    warning  Identifier 'most_recent_commit_date' is not in camel case   camelcase
  51:1    warning  Line 51 exceeds the maximum line length of 80               max-len
  51:7    warning  Unexpected console statement                                no-console
  51:18   warning  There must be a space inside this paren                     space-in-parens
  51:60   warning  There must be a space inside this paren                     space-in-parens
  51:84   warning  There must be a space inside this paren                     space-in-parens
  51:85   warning  There must be a space inside this paren                     space-in-parens
  52:3    error    Expected indentation of 4 space characters but found 2      indent
  52:14   warning  Unexpected space before function parentheses                space-before-function-paren
  53:5    warning  Unexpected console statement                                no-console

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/tile-map.js
   6:5   warning  'dateTranslate' is defined but never used                    no-unused-vars
   7:5   warning  'strToNum' is defined but never used                         no-unused-vars
   8:5   warning  'formatTime' is defined but never used                       no-unused-vars
  13:1   warning  Missing JSDoc comment                                        require-jsdoc
  15:7   warning  'defaultOpts' is defined but never used                      no-unused-vars
  18:21  error    A leading decimal point can be confused with a dot           no-floating-decimal
  22:4   error    Missing semicolon                                            semi
  31:3   warning  Missing JSDoc comment                                        require-jsdoc
  31:51  warning  'chartGroup' is defined but never used                       no-unused-vars
  34:36  error    Expected error to be handled                                 handle-callback-err
  36:11  warning  There must be a space inside this paren                      space-in-parens
  51:1   warning  Line 51 exceeds the maximum line length of 80                max-len
  57:35  error    Unexpected trailing comma                                    comma-dangle
  58:8   error    Missing semicolon                                            semi
  60:41  error    A constructor name should not start with a lowercase letter  new-cap
  65:25  error    A leading decimal point can be confused with a dot           no-floating-decimal
  69:8   error    Missing semicolon                                            semi
  71:11  warning  'tileMapChart' is defined but never used                     no-unused-vars
  86:4   error    Unnecessary semicolon                                        no-extra-semi

/Users/reedm/Repositories/cfpb/consumer-credit-trends/src/static/js/utils/dom.js
  32:9  error  Unexpected sync method: 'writeFileSync'  no-sync

/Users/reedm/Repositories/cfpb/consumer-credit-trends/gulp/tasks/browser-sync.js
  8:2  error  Expected indentation of 2 space characters but found 1  indent
```

**Comment by cfarm** [comment]
Thanks. ARGH I realize I should have a put a note on this PR that it isn't complete - it lints the following JS:

`/gulp`
`/src/static/js/templates`
`/src/static/js/utils`

The rest of the files in this folder still need linting:
`/src/static/js/`

I'll update today with a new PR

**Comment by cfarm** [comment]
Sorry for the confusion, y'all

**Pull request merged**
