### PR TITLE
Generate correct credit groupings and download icons on CSV file links

### PR DESCRIPTION
**Pull request by marteki**
This PR does two main things:

- updates the ranges for credit profiles in the generated code
- adds a file download icon using CSS to the CSV source file link

It also removes sample rules from the main LESS file that should have been deleted earlier.

## Additions

- Adds needed HTML tags and link modifiers to `src/static/js/templates/svg.hbs` to show the file download icon

## Removals

- Removes sample rules from `main.less`

## Changes

- Updates `src/static/js/templates/charts.js` and `data/README` to use the correct credit profile groupings

## Testing

`gulp build`, `gulp watch`, and `gulp release`.

- Check that the near prime and prime borrower risk profile charts have the correct credit groups (620 - 659 and 660 - 719 respectively) across all markets
- Make sure that all generated charts have the proper changes in the HTML to display the link modifier.

## Review

- @cfarm 
- @mistergone 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

After pasting into Wagtail, to get the proper styling:

screen shot 2016-12-19 at 5 59 43 pm

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by mistergone** [comment]
Works for me!

👍

**Comment by cfarm** [comment]
I wasn't very clear about this when presenting the gulp workflow, but I had planned for the release workflow/compiled files to only happen when we 'tag' and 'release' the project, not with every pull request. So I've been making changes to source files and then stashing my updated `/charts/` file changes with every branch and pull request.

Thinking behind this:

1. Makes it easier to review PR's (fewer files to review, only source files are diffed)
1. Reviewer is responsible for checking out the branch and testing it compiles successfully locally (helpful for catching bugs and doing QA)
1. Less potential for conflicts on compiled files

It does make it a bit confusing when compiling changes locally, so I'm open to suggestions on how to make that part easier. It also makes it more of a grey area on when to compile changes for sharing/getting design feedback on Github pages. I was hoping to move the compiled files to a build server type environment which builds from master and a staging one that builds from tagged releases, like we do with cf.gov. Ideas?  @marteki @mistergone @hillaryj

**Comment by cfarm** [comment]
I know the comment above didn't have anything to do with the content of this PR. I am checking it out locally rn :) Though looks like Chuck approved so this can merge. If so, let's close #44 which is a duplicate

**Comment by marteki** [comment]
@cfarm Well, crap. Why didn't I recognize that #44 was already addressing this? Sorry, I just picked a task off the sprint board and ran with it without checking to see if it was already done.

Also: that's very good to know about the chart HTML files. I'll remove them from this PR, and we can figure out the release process separately.

**Pull request merged**
